#!/bin/sh

# For WSL
# alias clip="clip.exe"

# Reload profile
if [ $SHELL = /bin/zsh ]; then
  alias src.="source ~/.zprofile"
fi
if [ $SHELL = /bin/bash ]; then
  alias src.="source ~/.bash_profile"
fi

# BASIC
## ls
case `uname` in
  Darwin)
    alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;say cache flushed'
    alias l='ls -GpF'
    alias ls='ls -GpF'
    alias ll='ls -alGpF'
    alias la="ls -aGpF"
  ;;
  Linux)
    alias l='ls --color=auto'
    alias ll='ls -al'
    alias ls='ls --color=auto'
    alias ipi="ip -br -c a"
  ;;
esac
## cd
alias c="cd"
alias ch="cd ~"
alias cx="cd .."
alias cxx="cd ../.."
alias cxxx="cd ../../.."
## grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
## vim, emacs
alias v="vim"
alias vedit="vim ~/.vimrc"
# alias memo="vim ~/dotfiles/memo.md"
## api
alias ipe="curl ipinfo.io/ip"
alias tenki="curl v2.wttr.in"
## etc
alias serveit="python -m SimpleHTTPServer"
alias makectags="ctags -R --exclude=.git --exclude=node_modules --exclude=test"
alias src="source"
alias penv="source bin/activate"
# for mac, jdate is unavailable
alias jdate="TZ=JST+15 date"
## interactive option
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias cl="clear"
# git shorthand
## add, status
alias ga="git add"
alias gs="git status"
## branch, checkout, diff, etc...
alias gb="git branch"
alias gc="git checkout"
alias gd="git diff"
### git fuzzy checkout, git fuzzy diff
#### switch current branch to a given branch
alias gfc="git branch | fzf | xargs git checkout"
#### compare current branch with a given branch
alias gfd='git branch | fzf | xargs -I {} git diff $(git branch --show-current) {}'
## git log
## TODO add more than current git log aliases
alias gl="git log --decorate --all"
alias glg="git log --decorate --all --graph"
alias glo="git log --decorate --all --oneline"
alias glgo="git log --decorate --all --oneline --graph"
## git commit with comment
alias gcm="git commit -m"
## git stash
alias gsh="git stash"
alias gsl="git stash list"
alias gss="git stash save"
alias gsa="git stash apply"
alias gsd="git stash drop"
# git: fix conflict
alias vimdiff="git mergetool -t vimdiff"

# docker
alias d="docker"
alias dl="docker logs"
alias drun="docker run"
alias dbuild="docker build"
alias dimg="docker images"
## docker ps
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dpsaq="docker ps -aq"
## docker rmi
alias drmi="docker rmi"
# alias drm-notags="docker rmi $(docker images -f 'dangling=true' -q)"
# alias drm-latest="docker rmi $(docker images *:latest -q)"
# docker-compose
alias fig="docker-compose"
alias dcu="docker-compose up"
alias dcd="docker-compose down"
alias dcd="docker-compose ps"
# docker-machine
alias dm="docker-machine"
alias dml="docker-machine ls"
# unsorted
alias dsh="docker exec -it"
# -d = exec deamon
alias dcud="docker-compose up -d" 
alias dcudb="docker-compose up -d --build" 

alias ddd="docker-compose run api python manage.py"

# quit
alias isv="ps ax | grep vim | grep -v grep"
alias killv="pgrep vim | xargs kill -9"

# sail
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
