# CPU Architecture
export ARCH=`uname -m`

# ENV Variables for PATH
USR=/usr/local/bin
export BREW=/opt/homebrew

MYCMD=$HOME/.bin
LOCAL_BIN=$HOME/.local/bin
export BREW_BIN=$BREW/bin
export BREW_SBIN=$BREW/sbin

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# PATH
PATH="$USR:$MYCMD:$LOCAL_BIN:$BREW_BIN:$BREW_SBIN:$PATH"

# mise
eval "$(mise activate zsh)"

# gcc
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"

# zoxide
eval "$(zoxide init zsh)"

# Load zprofile.local if exists
[ -f ~/.zprofile.local ] && source ~/.zprofile.local

# deduplicate PATH
typeset -U path PATH
