# CPU Architecture
# もう使わないかも
export ARCH=`uname -m`

# ENV Variables for PATH
export BREW=/opt/homebrew
export BREW_BIN=$BREW/bin
export BREW_SBIN=$BREW/sbin

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# PATH
PATH="$BREW_BIN:$BREW_SBIN:$PATH"

# gcc
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"

# mise
eval "$(mise activate zsh)"

# zoxide
eval "$(zoxide init zsh)"

# Load zprofile.local if exists
[ -f ~/.zprofile.local ] && source ~/.zprofile.local

# deduplicate PATH
typeset -U path PATH
