# CPU Architecture
export ARCH=`uname -m`

# ENV Variables for PATH
export USR=/usr/local/bin
export BREW=/opt/homebrew

export MYCMD=$HOME/.bin
export BREWBIN=$BREW/bin
export BREWSBIN=$BREW/sbin

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# PATH
PATH="$USR:$MYCMD:$BREWBIN:$BREWSBIN:$PATH"

# mise
eval "$(mise activate zsh)"

# gcc
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"

# java
export JAVA_HOME="$(/usr/libexec/java_home)"

# zoxide
eval "$(zoxide init zsh)"

# Load zprofile.local if exists
[ -f ~/.zprofile.local ] && source ~/.zprofile.local

# deduplicate PATH
typeset -U path PATH
