# Load aliases if exists
if [ -f "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# Homebrew
alias brew="/opt/homebrew/bin/brew"

# Directory
# cd すると自動でpushd する
setopt autopushd

# pushd に同じディレクトリを重複させない
setopt pushdignoredups

# Command History
HISTSIZE=10000
HISTFILESIZE=10000

## Command History Fuzzy Search (Only Zsh)
# コマンド履歴をfzf で検索する
alias fcf="fc -ln 1 | sort | uniq | sort -r | fzf"

## 全体のコマンド履歴の数を表示
alias fcc="fc -l 1 | wc -l"

# 他のウィンドウとコマンド履歴を共有する
setopt share_history

## 連続して繰り返し実行されたコマンドは、履歴に追加しない
HISTCONTROL=ignoredups


# Prompt
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

## git-prompt
source $HOME/.git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUPSTREAM=1
GIT_PS1_SHOWUNTRACKEDFILES=
GIT_PS1_SHOWSTASHSTATE=1

precmd() {
    __git_ps1 %n@${ARCH}$%~ '%# ' ' (%s)'
}

## Starship
[ -f ~/.config/starship.toml ] && eval "$(starship init zsh)"

# 補完系
# zsh-completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  # zsh-autosuggestions
  source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

  autoload -Uz compinit && compinit
fi

# タブを一回押すと候補一覧を表示
setopt auto_list
# 続けてタブを押すと順番に補完
setopt auto_menu

## 補完システムと履歴からサジェストを取得する
ZSH_AUTOSUGGEST_STRATEGY=(completion history)

# Load zshrc.local if exists
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# zsh-syntax-highlighting (最後に読み込む必要がある)
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

