"" basic setting
" disable unused features
set nobackup           "バックアップファイルの出力を無効にする
set noswapfile         "swpファイルの出力を無効にする
set autoread           "編集中のファイルが変更されたら自動で読み直す

" interface
syntax on
set number             "行番号を表示
set autoindent         "改行時に自動でインデントする
set clipboard=unnamed  "ヤンクした文字列をクリップボードにコピー
set cursorline         "現在の行を強調表示
set showmatch          "入力したコマンドを画面右下に表示する
set wildmenu           "コマンドライン補完が拡張モードで行われる
set visualbell         "ビープ音を可視化
"* 挿入モードでバックスペースでの文字削除を有効にする
"* Viではバックスペースでの削除が出来ない
set backspace=indent,eol,start

" encoding
set encoding=utf-8     "エンコードをutf-8に指定
set fileencodings=utf-8,euc-jp,sjis,iso-2022-jp
set fileformats=unix,dos,mac
scriptencoding utf-8

" tab
set expandtab          "タブ入力を空白に変換
set tabstop=4          "タブを何文字の空白に変換するか
set shiftwidth=4       "自動インデント時に入力する空白の数

" search
set hlsearch           "検索した文字をハイライトする
set ignorecase         "大文字小文字を区別しないで検索する
set smartcase          "大文字が含まれている場合は"ignorecase"を上書きする
set incsearch          "入力時に順次対象文字列にヒットさせる
set wrapscan           "検索が末尾まで進んだら先頭から再び検索する

" Typescript
augroup FiletypeGroup
    autocmd!
    " .ts is a Typescript file
    au BufNewFile,BufRead *.ts set filetype=typescript
augroup END

" Indent
if has("autocmd")
  filetype plugin on
  filetype indent on
  autocmd FileType c           setlocal sw=4 sts=4 ts=4 et
  autocmd FileType html        setlocal sw=2 sts=2 ts=2 et
  autocmd FileType ruby        setlocal sw=2 sts=2 ts=2 et
  autocmd FileType css         setlocal sw=2 sts=2 ts=2 et
  autocmd FileType typescript  setlocal sw=4 sts=4 ts=4 et
  autocmd FileType javascript  setlocal sw=4 sts=4 ts=4 et
  autocmd FileType java        setlocal sw=4 sts=4 ts=4 et
  autocmd FileType zsh         setlocal sw=4 sts=4 ts=4 et
  autocmd FileType python      setlocal sw=4 sts=4 ts=4 et
  autocmd FileType json        setlocal sw=4 sts=4 ts=4 et
endif

" netrw
"* set defautl view to tree view
let g:netrw_liststyle = 3

"" Advance setting
" key mapping
inoremap {{ {}<Left>
inoremap {<Enter> {}<Left><CR><ESC><S-o>
inoremap (( ()<ESC>i
inoremap (<Enter> ()<Left><CR><ESC><S-o>
inoremap [[ []<ESC>i
inoremap [<Enter> []<Left><CR><ESC><S-o>
inoremap << <><ESC>i
inoremap "" ""<LEFT>
inoremap '' ''<LEFT>
inoremap `` ``<LEFT>

" inoremap || ||<LEFT>
"* ノーマルモード
"* 文字列が折り返されていても一行ずつ移動
noremap j gj
noremap k gk
"* "H", "L"で行頭・行末に移動
noremap <S-h>   ^
noremap <S-l>   $
" ESC連打でハイライト解除
nmap <Esc><Esc> :nohlsearch<CR><Esc>
nnoremap <C-]> g<C-]> 
" 挿入モード
inoremap <C-]> <ESC>g<C-]> 
" jk同時押しで挿入モードを抜ける
inoremap jk <ESC> 
inoremap kj <ESC>
inoremap <C-b> <Left>
inoremap <C-f> <Right>
" コマンドラインモード
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>
" leader
let mapleader = "\<Space>"

" Tag jump
set tags=./tags;$HOME
