return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',
    opts = {
      indent = { enable = true },
      highlight = { enable = true },
      folds = { enable = true },
      -- Supported languages:
      -- https://github.com/nvim-treesitter/nvim-treesitter/blob/main/SUPPORTED_LANGUAGES.md
      ensure_installed = {
        "astro",
        "awk",
        "bash",
        "c",
        "css",
        "diff",
        "dockerfile",
        "editorconfig",
        "gnuplot",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "perl",
        "printf",
        "python",
        "query",
        "regex",
        "ruby",
        "scheme",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
    },
  },
}
